### ISSUE TITLE
Failed to load ThievingSlimes 1.0.1 with SlimyBoyos 3.1.0.19

### ISSUE THREAD

**Issue by Meskino** [pitbox46/ThievingSlimes#1]
ThievingSlimes requires a version of SlimyBoyos greater than or equal to 3.1.0.10 and I have 3.1.0.19 but it recognizes it as 3.1.0
I only have these two mods installed in my minecraft mods folder.
below I will specify the versions of each file.

Minecraft Version: 1.16.5
Forge Version: 36.1.23
ThievingSlimes Version: 1.0.1
SlimyBoyos Version: 3.1.0.19

here I will leave the crash and log files

Crash: [crash-2021-05-19_00.28.26-fml.txt](https://github.com/pitbox46/ThievingSlimes/files/6505678/crash-2021-05-19_00.28.26-fml.txt)

Latest Log: [crash-2021-05-19_00.28.26-fml.txt](https://github.com/pitbox46/ThievingSlimes/files/6505686/crash-2021-05-19_00.28.26-fml.txt)

**Comment by pitbox46** [comment]
It looks like this issue is with Slimy Boyos rather than my mod. I opened up an issue on the Slimy Boyos github. [Link to issue](https://github.com/jaredlll08/SlimyBoyos/issues/10)

**Comment by pitbox46** [comment]
Should be fixed with the next Slimy Boyos patch
